-- Cartty Store | Breakfast Set 01 | qb-core
-- Docs: https://cartty.gitbook.io/cartty-docs/documentation/food-props/breakfast-set-01
-- Discord: https://discord.gg/4EXtjUjuKQ

['cartty_breakfast_waffle02']    = { name='cartty_breakfast_waffle02',    label='Waffle',                  weight=380, type='item', image='cartty_breakfast_waffle02.png',    unique=false, useable=true, shouldClose=true, combinable=nil, description='A stack of golden waffles with butter and syrup.' },
['cartty_breakfast_pancake01']   = { name='cartty_breakfast_pancake01',   label='Pancakes',                weight=380, type='item', image='cartty_breakfast_pancake01.png',   unique=false, useable=true, shouldClose=true, combinable=nil, description='Fluffy pancakes served warm with syrup.' },
['cartty_breakfast_eggbacon01']  = { name='cartty_breakfast_eggbacon01',  label='Eggs and Bacon',          weight=420, type='item', image='cartty_breakfast_eggbacon01.png',  unique=false, useable=true, shouldClose=true, combinable=nil, description='Fried eggs with crisp bacon strips.' },
['cartty_breakfast_eggbacon02']  = { name='cartty_breakfast_eggbacon02',  label='Full Breakfast',          weight=450, type='item', image='cartty_breakfast_eggbacon02.png',  unique=false, useable=true, shouldClose=true, combinable=nil, description='Eggs, bacon, sausage and beans on one plate.' },
['cartty_breakfast_toast01']     = { name='cartty_breakfast_toast01',     label='Toast',                   weight=120, type='item', image='cartty_breakfast_toast01.png',     unique=false, useable=true, shouldClose=true, combinable=nil, description='Two slices of lightly toasted bread.' },
['cartty_breakfast_toast02']     = { name='cartty_breakfast_toast02',     label='Toast with Jam',          weight=140, type='item', image='cartty_breakfast_toast02.png',     unique=false, useable=true, shouldClose=true, combinable=nil, description='Toasted bread spread with fruit jam.' },
['cartty_breakfast_bagel01']     = { name='cartty_breakfast_bagel01',     label='Sesame Bagel',            weight=180, type='item', image='cartty_breakfast_bagel01.png',     unique=false, useable=true, shouldClose=true, combinable=nil, description='A chewy bagel topped with sesame seeds.' },
['cartty_breakfast_bagel02']     = { name='cartty_breakfast_bagel02',     label='Bagel with Cream Cheese', weight=200, type='item', image='cartty_breakfast_bagel02.png',     unique=false, useable=true, shouldClose=true, combinable=nil, description='A sliced bagel filled with soft cream cheese.' },
['cartty_breakfast_croissant01'] = { name='cartty_breakfast_croissant01', label='Croissant',               weight=150, type='item', image='cartty_breakfast_croissant01.png', unique=false, useable=true, shouldClose=true, combinable=nil, description='A flaky butter croissant, fresh from the oven.' },
['cartty_breakfast_mug01']       = { name='cartty_breakfast_mug01',       label='Coffee',                  weight=300, type='item', image='cartty_breakfast_mug01.png',       unique=false, useable=true, shouldClose=true, combinable=nil, description='A hot mug of black filter coffee.' },
['cartty_breakfast_mug02']       = { name='cartty_breakfast_mug02',       label='Latte',                   weight=300, type='item', image='cartty_breakfast_mug02.png',       unique=false, useable=true, shouldClose=true, combinable=nil, description='Espresso topped with steamed milk.' },
['cartty_breakfast_juice01']     = { name='cartty_breakfast_juice01',     label='Orange Juice',            weight=320, type='item', image='cartty_breakfast_juice01.png',     unique=false, useable=true, shouldClose=true, combinable=nil, description='A tall glass of freshly squeezed orange juice.' },
['cartty_breakfast_milk01']      = { name='cartty_breakfast_milk01',      label='Milk',                    weight=320, type='item', image='cartty_breakfast_milk01.png',      unique=false, useable=true, shouldClose=true, combinable=nil, description='A cold glass of whole milk.' },
['cartty_breakfast_cherry01']    = { name='cartty_breakfast_cherry01',    label='Cherry Juice',            weight=320, type='item', image='cartty_breakfast_cherry01.png',    unique=false, useable=true, shouldClose=true, combinable=nil, description='A glass of sweet-tart cherry juice.' },
