-- Cartty Store | Living Room 01 | Ps-Housing
-- Docs: https://cartty.gitbook.io/cartty-docs/documentation/props/living-room-01
-- Discord: https://discord.gg/4EXtjUjuKQ

{
    category = "Living Room",
    items = {
        -- Couches
        { ["object"] = "cartty_lr01_couch01_c01", ["price"] = 0, ["label"] = "Couch C01" },
        { ["object"] = "cartty_lr01_couch01_c02", ["price"] = 0, ["label"] = "Couch C02" },
        { ["object"] = "cartty_lr01_couch01_c03", ["price"] = 0, ["label"] = "Couch C03" },
        { ["object"] = "cartty_lr01_couch01_c04", ["price"] = 0, ["label"] = "Couch C04" },
        { ["object"] = "cartty_lr01_couch01_c05", ["price"] = 0, ["label"] = "Couch C05" },
        { ["object"] = "cartty_lr01_couch01_c06", ["price"] = 0, ["label"] = "Couch C06" },
        { ["object"] = "cartty_lr01_couch01_c07", ["price"] = 0, ["label"] = "Couch C07" },
        { ["object"] = "cartty_lr01_couch01_d01", ["price"] = 0, ["label"] = "Couch D01" },
        { ["object"] = "cartty_lr01_couch01_d02", ["price"] = 0, ["label"] = "Couch D02" },
        { ["object"] = "cartty_lr01_couch01_d03", ["price"] = 0, ["label"] = "Couch D03" },
        { ["object"] = "cartty_lr01_couch01_d04", ["price"] = 0, ["label"] = "Couch D04" },
        { ["object"] = "cartty_lr01_couch01_d05", ["price"] = 0, ["label"] = "Couch D05" },
        { ["object"] = "cartty_lr01_couch01_d06", ["price"] = 0, ["label"] = "Couch D06" },
        { ["object"] = "cartty_lr01_couch01_d07", ["price"] = 0, ["label"] = "Couch D07" },
        { ["object"] = "cartty_lr01_couch01_e01", ["price"] = 0, ["label"] = "Couch E01" },
        { ["object"] = "cartty_lr01_couch01_e02", ["price"] = 0, ["label"] = "Couch E02" },
        { ["object"] = "cartty_lr01_couch01_e03", ["price"] = 0, ["label"] = "Couch E03" },
        { ["object"] = "cartty_lr01_couch01_e04", ["price"] = 0, ["label"] = "Couch E04" },
        { ["object"] = "cartty_lr01_couch01_e05", ["price"] = 0, ["label"] = "Couch E05" },
        { ["object"] = "cartty_lr01_couch01_e06", ["price"] = 0, ["label"] = "Couch E06" },
        { ["object"] = "cartty_lr01_couch01_e07", ["price"] = 0, ["label"] = "Couch E07" },
        { ["object"] = "cartty_lr01_couch01_f01", ["price"] = 0, ["label"] = "Couch F01" },
        { ["object"] = "cartty_lr01_couch01_f02", ["price"] = 0, ["label"] = "Couch F02" },
        { ["object"] = "cartty_lr01_couch01_f03", ["price"] = 0, ["label"] = "Couch F03" },
        { ["object"] = "cartty_lr01_couch01_f04", ["price"] = 0, ["label"] = "Couch F04" },
        { ["object"] = "cartty_lr01_couch01_f05", ["price"] = 0, ["label"] = "Couch F05" },
        { ["object"] = "cartty_lr01_couch01_f06", ["price"] = 0, ["label"] = "Couch F06" },
        { ["object"] = "cartty_lr01_couch01_f07", ["price"] = 0, ["label"] = "Couch F07" },
        { ["object"] = "cartty_lr01_couch01_g01", ["price"] = 0, ["label"] = "Couch G01" },
        { ["object"] = "cartty_lr01_couch01_g02", ["price"] = 0, ["label"] = "Couch G02" },
        { ["object"] = "cartty_lr01_couch01_g03", ["price"] = 0, ["label"] = "Couch G03" },
        { ["object"] = "cartty_lr01_couch01_g04", ["price"] = 0, ["label"] = "Couch G04" },
        { ["object"] = "cartty_lr01_couch01_g05", ["price"] = 0, ["label"] = "Couch G05" },
        { ["object"] = "cartty_lr01_couch01_g06", ["price"] = 0, ["label"] = "Couch G06" },
        { ["object"] = "cartty_lr01_couch01_g07", ["price"] = 0, ["label"] = "Couch G07" },
        { ["object"] = "cartty_lr01_couch01_l01", ["price"] = 0, ["label"] = "Couch L01" },
        { ["object"] = "cartty_lr01_couch01_l02", ["price"] = 0, ["label"] = "Couch L02" },
        { ["object"] = "cartty_lr01_couch01_l03", ["price"] = 0, ["label"] = "Couch L03" },
        { ["object"] = "cartty_lr01_couch01_l04", ["price"] = 0, ["label"] = "Couch L04" },
        { ["object"] = "cartty_lr01_couch01_l05", ["price"] = 0, ["label"] = "Couch L05" },
        { ["object"] = "cartty_lr01_couch01_l06", ["price"] = 0, ["label"] = "Couch L06" },
        { ["object"] = "cartty_lr01_couch01_l07", ["price"] = 0, ["label"] = "Couch L07" },
        { ["object"] = "cartty_lr01_couch01_m01", ["price"] = 0, ["label"] = "Couch M01" },
        { ["object"] = "cartty_lr01_couch01_m02", ["price"] = 0, ["label"] = "Couch M02" },
        { ["object"] = "cartty_lr01_couch01_m03", ["price"] = 0, ["label"] = "Couch M03" },
        { ["object"] = "cartty_lr01_couch01_m04", ["price"] = 0, ["label"] = "Couch M04" },
        { ["object"] = "cartty_lr01_couch01_m05", ["price"] = 0, ["label"] = "Couch M05" },
        { ["object"] = "cartty_lr01_couch01_m06", ["price"] = 0, ["label"] = "Couch M06" },
        { ["object"] = "cartty_lr01_couch01_m07", ["price"] = 0, ["label"] = "Couch M07" },
        { ["object"] = "cartty_lr01_couch01_o01", ["price"] = 0, ["label"] = "Couch O01" },
        { ["object"] = "cartty_lr01_couch01_o02", ["price"] = 0, ["label"] = "Couch O02" },
        { ["object"] = "cartty_lr01_couch01_o03", ["price"] = 0, ["label"] = "Couch O03" },
        { ["object"] = "cartty_lr01_couch01_o04", ["price"] = 0, ["label"] = "Couch O04" },
        { ["object"] = "cartty_lr01_couch01_o05", ["price"] = 0, ["label"] = "Couch O05" },
        { ["object"] = "cartty_lr01_couch01_o06", ["price"] = 0, ["label"] = "Couch O06" },
        { ["object"] = "cartty_lr01_couch01_o07", ["price"] = 0, ["label"] = "Couch O07" },
        { ["object"] = "cartty_lr01_couch01_p01", ["price"] = 0, ["label"] = "Couch P01" },
        { ["object"] = "cartty_lr01_couch01_p02", ["price"] = 0, ["label"] = "Couch P02" },
        { ["object"] = "cartty_lr01_couch01_p03", ["price"] = 0, ["label"] = "Couch P03" },
        { ["object"] = "cartty_lr01_couch01_p04", ["price"] = 0, ["label"] = "Couch P04" },
        { ["object"] = "cartty_lr01_couch01_p05", ["price"] = 0, ["label"] = "Couch P05" },
        { ["object"] = "cartty_lr01_couch01_p06", ["price"] = 0, ["label"] = "Couch P06" },
        { ["object"] = "cartty_lr01_couch01_p07", ["price"] = 0, ["label"] = "Couch P07" },
        { ["object"] = "cartty_lr01_couch01_r01", ["price"] = 0, ["label"] = "Couch R01" },
        { ["object"] = "cartty_lr01_couch01_r02", ["price"] = 0, ["label"] = "Couch R02" },
        { ["object"] = "cartty_lr01_couch01_r03", ["price"] = 0, ["label"] = "Couch R03" },
        { ["object"] = "cartty_lr01_couch01_r04", ["price"] = 0, ["label"] = "Couch R04" },
        { ["object"] = "cartty_lr01_couch01_r05", ["price"] = 0, ["label"] = "Couch R05" },
        { ["object"] = "cartty_lr01_couch01_r06", ["price"] = 0, ["label"] = "Couch R06" },
        { ["object"] = "cartty_lr01_couch01_r07", ["price"] = 0, ["label"] = "Couch R07" },

        -- Lamps
        { ["object"] = "cartty_lr01_desklamp0101", ["price"] = 0, ["label"] = "Desk Lamp 01 A" },
        { ["object"] = "cartty_lr01_desklamp0102", ["price"] = 0, ["label"] = "Desk Lamp 01 B" },
        { ["object"] = "cartty_lr01_lamp0101", ["price"] = 0, ["label"] = "Lamp 01 A" },
        { ["object"] = "cartty_lr01_lamp0102", ["price"] = 0, ["label"] = "Lamp 01 B" },

        -- Rugs
        { ["object"] = "cartty_lr01_rug0101", ["price"] = 0, ["label"] = "Rug 01 A" },
        { ["object"] = "cartty_lr01_rug0102", ["price"] = 0, ["label"] = "Rug 01 B" },
        { ["object"] = "cartty_lr01_rug0103", ["price"] = 0, ["label"] = "Rug 01 C" },
        { ["object"] = "cartty_lr01_rug0104", ["price"] = 0, ["label"] = "Rug 01 D" },
        { ["object"] = "cartty_lr01_rug0105", ["price"] = 0, ["label"] = "Rug 01 E" },
        { ["object"] = "cartty_lr01_rug0106", ["price"] = 0, ["label"] = "Rug 01 F" },
        { ["object"] = "cartty_lr01_rug0107", ["price"] = 0, ["label"] = "Rug 01 G" },
        { ["object"] = "cartty_lr01_rug0201", ["price"] = 0, ["label"] = "Rug 02 A" },
        { ["object"] = "cartty_lr01_rug0202", ["price"] = 0, ["label"] = "Rug 02 B" },
        { ["object"] = "cartty_lr01_rug0203", ["price"] = 0, ["label"] = "Rug 02 C" },
        { ["object"] = "cartty_lr01_rug0204", ["price"] = 0, ["label"] = "Rug 02 D" },
        { ["object"] = "cartty_lr01_rug0205", ["price"] = 0, ["label"] = "Rug 02 E" },
        { ["object"] = "cartty_lr01_rug0206", ["price"] = 0, ["label"] = "Rug 02 F" },
        { ["object"] = "cartty_lr01_rug0207", ["price"] = 0, ["label"] = "Rug 02 G" },
        { ["object"] = "cartty_lr01_rug0301", ["price"] = 0, ["label"] = "Rug 03 A" },
        { ["object"] = "cartty_lr01_rug0302", ["price"] = 0, ["label"] = "Rug 03 B" },
        { ["object"] = "cartty_lr01_rug0303", ["price"] = 0, ["label"] = "Rug 03 C" },
        { ["object"] = "cartty_lr01_rug0304", ["price"] = 0, ["label"] = "Rug 03 D" },
        { ["object"] = "cartty_lr01_rug0305", ["price"] = 0, ["label"] = "Rug 03 E" },
        { ["object"] = "cartty_lr01_rug0306", ["price"] = 0, ["label"] = "Rug 03 F" },
        { ["object"] = "cartty_lr01_rug0307", ["price"] = 0, ["label"] = "Rug 03 G" },

        -- Tables
        { ["object"] = "cartty_lr01_table01_01", ["price"] = 0, ["label"] = "Table 01 A" },
        { ["object"] = "cartty_lr01_table01_02", ["price"] = 0, ["label"] = "Table 01 B" },
        { ["object"] = "cartty_lr01_table01_03", ["price"] = 0, ["label"] = "Table 01 C" },
        { ["object"] = "cartty_lr01_table01_04", ["price"] = 0, ["label"] = "Table 01 D" },
        { ["object"] = "cartty_lr01_table01_05", ["price"] = 0, ["label"] = "Table 01 E" },
        { ["object"] = "cartty_lr01_table01_06", ["price"] = 0, ["label"] = "Table 01 F" },
        { ["object"] = "cartty_lr01_table01_07", ["price"] = 0, ["label"] = "Table 01 G" },
        { ["object"] = "cartty_lr01_table02_01", ["price"] = 0, ["label"] = "Table 02 A" },
        { ["object"] = "cartty_lr01_table02_02", ["price"] = 0, ["label"] = "Table 02 B" },
        { ["object"] = "cartty_lr01_table02_03", ["price"] = 0, ["label"] = "Table 02 C" },
        { ["object"] = "cartty_lr01_table02_04", ["price"] = 0, ["label"] = "Table 02 D" },
        { ["object"] = "cartty_lr01_table02_05", ["price"] = 0, ["label"] = "Table 02 E" },
        { ["object"] = "cartty_lr01_table02_06", ["price"] = 0, ["label"] = "Table 02 F" },
        { ["object"] = "cartty_lr01_table02_07", ["price"] = 0, ["label"] = "Table 02 G" },
        { ["object"] = "cartty_lr01_table03_01", ["price"] = 0, ["label"] = "Table 03 A" },
        { ["object"] = "cartty_lr01_table03_02", ["price"] = 0, ["label"] = "Table 03 B" },
        { ["object"] = "cartty_lr01_table03_03", ["price"] = 0, ["label"] = "Table 03 C" },
        { ["object"] = "cartty_lr01_table03_04", ["price"] = 0, ["label"] = "Table 03 D" },
        { ["object"] = "cartty_lr01_table03_05", ["price"] = 0, ["label"] = "Table 03 E" },
        { ["object"] = "cartty_lr01_table03_06", ["price"] = 0, ["label"] = "Table 03 F" },
        { ["object"] = "cartty_lr01_table03_07", ["price"] = 0, ["label"] = "Table 03 G" },
    }
}
