-- Cartty Store | Housing Stairs 01 | BCS Housing V3
-- Docs: https://cartty.gitbook.io/cartty-docs/documentation/props/housing-stairs-01
-- Discord: https://discord.gg/4EXtjUjuKQ

return {
    label = 'Stairs01',
    hidden = false,
    list = {
        -- As
        { label = "A FLAT01", model = "cartty_hstairs01_a_flat01", price = 0 },
        { label = "A FLAT02", model = "cartty_hstairs01_a_flat02", price = 0 },
        { label = "A STAIR01", model = "cartty_hstairs01_a_stair01", price = 0 },
        { label = "A STAIR02", model = "cartty_hstairs01_a_stair02", price = 0 },
        { label = "A STAIR03", model = "cartty_hstairs01_a_stair03", price = 0 },
        { label = "A STAIR04", model = "cartty_hstairs01_a_stair04", price = 0 },
        { label = "A STAIR05", model = "cartty_hstairs01_a_stair05", price = 0 },
        { label = "A STAIR06", model = "cartty_hstairs01_a_stair06", price = 0 },
        { label = "A STAIR07", model = "cartty_hstairs01_a_stair07", price = 0 },
        { label = "A STAIR08", model = "cartty_hstairs01_a_stair08", price = 0 },
        { label = "A STAIR09", model = "cartty_hstairs01_a_stair09", price = 0 },
        { label = "A STAIR10", model = "cartty_hstairs01_a_stair10", price = 0 },
        { label = "A STAIR11", model = "cartty_hstairs01_a_stair11", price = 0 },
        { label = "A STAIR12", model = "cartty_hstairs01_a_stair12", price = 0 },
        -- Bs
        { label = "B FLAT01", model = "cartty_hstairs01_b_flat01", price = 0 },
        { label = "B FLAT02", model = "cartty_hstairs01_b_flat02", price = 0 },
        { label = "B STAIR01", model = "cartty_hstairs01_b_stair01", price = 0 },
        { label = "B STAIR02", model = "cartty_hstairs01_b_stair02", price = 0 },
        { label = "B STAIR03", model = "cartty_hstairs01_b_stair03", price = 0 },
        { label = "B STAIR04", model = "cartty_hstairs01_b_stair04", price = 0 },
        { label = "B STAIR05", model = "cartty_hstairs01_b_stair05", price = 0 },
        { label = "B STAIR06", model = "cartty_hstairs01_b_stair06", price = 0 },
        { label = "B STAIR07", model = "cartty_hstairs01_b_stair07", price = 0 },
        { label = "B STAIR08", model = "cartty_hstairs01_b_stair08", price = 0 },
        { label = "B STAIR09", model = "cartty_hstairs01_b_stair09", price = 0 },
        { label = "B STAIR10", model = "cartty_hstairs01_b_stair10", price = 0 },
        { label = "B STAIR11", model = "cartty_hstairs01_b_stair11", price = 0 },
        { label = "B STAIR12", model = "cartty_hstairs01_b_stair12", price = 0 },
        -- Cs
        { label = "C FLAT01", model = "cartty_hstairs01_c_flat01", price = 0 },
        { label = "C FLAT02", model = "cartty_hstairs01_c_flat02", price = 0 },
        { label = "C STAIR01", model = "cartty_hstairs01_c_stair01", price = 0 },
        { label = "C STAIR02", model = "cartty_hstairs01_c_stair02", price = 0 },
        { label = "C STAIR03", model = "cartty_hstairs01_c_stair03", price = 0 },
        { label = "C STAIR04", model = "cartty_hstairs01_c_stair04", price = 0 },
        { label = "C STAIR05", model = "cartty_hstairs01_c_stair05", price = 0 },
        { label = "C STAIR06", model = "cartty_hstairs01_c_stair06", price = 0 },
        { label = "C STAIR07", model = "cartty_hstairs01_c_stair07", price = 0 },
        { label = "C STAIR08", model = "cartty_hstairs01_c_stair08", price = 0 },
        { label = "C STAIR09", model = "cartty_hstairs01_c_stair09", price = 0 },
        { label = "C STAIR10", model = "cartty_hstairs01_c_stair10", price = 0 },
        { label = "C STAIR11", model = "cartty_hstairs01_c_stair11", price = 0 },
        { label = "C STAIR12", model = "cartty_hstairs01_c_stair12", price = 0 },
        -- Ds
        { label = "D FLAT01", model = "cartty_hstairs01_d_flat01", price = 0 },
        { label = "D FLAT02", model = "cartty_hstairs01_d_flat02", price = 0 },
        { label = "D STAIR01", model = "cartty_hstairs01_d_stair01", price = 0 },
        { label = "D STAIR02", model = "cartty_hstairs01_d_stair02", price = 0 },
        { label = "D STAIR03", model = "cartty_hstairs01_d_stair03", price = 0 },
        { label = "D STAIR04", model = "cartty_hstairs01_d_stair04", price = 0 },
        { label = "D STAIR05", model = "cartty_hstairs01_d_stair05", price = 0 },
        { label = "D STAIR06", model = "cartty_hstairs01_d_stair06", price = 0 },
        { label = "D STAIR07", model = "cartty_hstairs01_d_stair07", price = 0 },
        { label = "D STAIR08", model = "cartty_hstairs01_d_stair08", price = 0 },
        { label = "D STAIR09", model = "cartty_hstairs01_d_stair09", price = 0 },
        { label = "D STAIR10", model = "cartty_hstairs01_d_stair10", price = 0 },
        { label = "D STAIR11", model = "cartty_hstairs01_d_stair11", price = 0 },
        { label = "D STAIR12", model = "cartty_hstairs01_d_stair12", price = 0 },
        -- Es
        { label = "E FLAT01", model = "cartty_hstairs01_e_flat01", price = 0 },
        { label = "E FLAT02", model = "cartty_hstairs01_e_flat02", price = 0 },
        { label = "E STAIR01", model = "cartty_hstairs01_e_stair01", price = 0 },
        { label = "E STAIR02", model = "cartty_hstairs01_e_stair02", price = 0 },
        { label = "E STAIR03", model = "cartty_hstairs01_e_stair03", price = 0 },
        { label = "E STAIR04", model = "cartty_hstairs01_e_stair04", price = 0 },
        { label = "E STAIR05", model = "cartty_hstairs01_e_stair05", price = 0 },
        { label = "E STAIR06", model = "cartty_hstairs01_e_stair06", price = 0 },
        { label = "E STAIR07", model = "cartty_hstairs01_e_stair07", price = 0 },
        { label = "E STAIR08", model = "cartty_hstairs01_e_stair08", price = 0 },
        { label = "E STAIR09", model = "cartty_hstairs01_e_stair09", price = 0 },
        { label = "E STAIR10", model = "cartty_hstairs01_e_stair10", price = 0 },
        { label = "E STAIR11", model = "cartty_hstairs01_e_stair11", price = 0 },
        { label = "E STAIR12", model = "cartty_hstairs01_e_stair12", price = 0 },
        -- Fs
        { label = "F STAIR03", model = "cartty_hstairs01_f_stair03", price = 0 },
        { label = "F STAIR04", model = "cartty_hstairs01_f_stair04", price = 0 },
        { label = "F STAIR05", model = "cartty_hstairs01_f_stair05", price = 0 },
        { label = "F STAIR06", model = "cartty_hstairs01_f_stair06", price = 0 },
        { label = "F STAIR07", model = "cartty_hstairs01_f_stair07", price = 0 },
        { label = "F STAIR08", model = "cartty_hstairs01_f_stair08", price = 0 },
        { label = "F STAIR09", model = "cartty_hstairs01_f_stair09", price = 0 },
        { label = "F STAIR10", model = "cartty_hstairs01_f_stair10", price = 0 },
        { label = "F STAIR11", model = "cartty_hstairs01_f_stair11", price = 0 },
        { label = "F STAIR12", model = "cartty_hstairs01_f_stair12", price = 0 },
        -- Gs
        { label = "G STAIR03", model = "cartty_hstairs01_g_stair03", price = 0 },
        { label = "G STAIR04", model = "cartty_hstairs01_g_stair04", price = 0 },
        { label = "G STAIR05", model = "cartty_hstairs01_g_stair05", price = 0 },
        { label = "G STAIR06", model = "cartty_hstairs01_g_stair06", price = 0 },
        { label = "G STAIR07", model = "cartty_hstairs01_g_stair07", price = 0 },
        { label = "G STAIR08", model = "cartty_hstairs01_g_stair08", price = 0 },
        { label = "G STAIR09", model = "cartty_hstairs01_g_stair09", price = 0 },
        { label = "G STAIR10", model = "cartty_hstairs01_g_stair10", price = 0 },
        { label = "G STAIR11", model = "cartty_hstairs01_g_stair11", price = 0 },
        { label = "G STAIR12", model = "cartty_hstairs01_g_stair12", price = 0 },
        -- Hs
        { label = "H STAIR03", model = "cartty_hstairs01_h_stair03", price = 0 },
        { label = "H STAIR04", model = "cartty_hstairs01_h_stair04", price = 0 },
        { label = "H STAIR05", model = "cartty_hstairs01_h_stair05", price = 0 },
        { label = "H STAIR06", model = "cartty_hstairs01_h_stair06", price = 0 },
        { label = "H STAIR07", model = "cartty_hstairs01_h_stair07", price = 0 },
        { label = "H STAIR08", model = "cartty_hstairs01_h_stair08", price = 0 },
        { label = "H STAIR09", model = "cartty_hstairs01_h_stair09", price = 0 },
        { label = "H STAIR10", model = "cartty_hstairs01_h_stair10", price = 0 },
        { label = "H STAIR11", model = "cartty_hstairs01_h_stair11", price = 0 },
        { label = "H STAIR12", model = "cartty_hstairs01_h_stair12", price = 0 },
        -- Is
        { label = "I STAIR03", model = "cartty_hstairs01_i_stair03", price = 0 },
        { label = "I STAIR04", model = "cartty_hstairs01_i_stair04", price = 0 },
        { label = "I STAIR05", model = "cartty_hstairs01_i_stair05", price = 0 },
        { label = "I STAIR06", model = "cartty_hstairs01_i_stair06", price = 0 },
        { label = "I STAIR07", model = "cartty_hstairs01_i_stair07", price = 0 },
        { label = "I STAIR08", model = "cartty_hstairs01_i_stair08", price = 0 },
        { label = "I STAIR09", model = "cartty_hstairs01_i_stair09", price = 0 },
        { label = "I STAIR10", model = "cartty_hstairs01_i_stair10", price = 0 },
        { label = "I STAIR11", model = "cartty_hstairs01_i_stair11", price = 0 },
        { label = "I STAIR12", model = "cartty_hstairs01_i_stair12", price = 0 },
        -- Js
        { label = "J STAIR03", model = "cartty_hstairs01_j_stair03", price = 0 },
        { label = "J STAIR04", model = "cartty_hstairs01_j_stair04", price = 0 },
        { label = "J STAIR05", model = "cartty_hstairs01_j_stair05", price = 0 },
        { label = "J STAIR06", model = "cartty_hstairs01_j_stair06", price = 0 },
        { label = "J STAIR07", model = "cartty_hstairs01_j_stair07", price = 0 },
        { label = "J STAIR08", model = "cartty_hstairs01_j_stair08", price = 0 },
        { label = "J STAIR09", model = "cartty_hstairs01_j_stair09", price = 0 },
        { label = "J STAIR10", model = "cartty_hstairs01_j_stair10", price = 0 },
        { label = "J STAIR11", model = "cartty_hstairs01_j_stair11", price = 0 },
        { label = "J STAIR12", model = "cartty_hstairs01_j_stair12", price = 0 },
        -- Ks
        { label = "K STAIR03", model = "cartty_hstairs01_k_stair03", price = 0 },
        { label = "K STAIR04", model = "cartty_hstairs01_k_stair04", price = 0 },
        { label = "K STAIR05", model = "cartty_hstairs01_k_stair05", price = 0 },
        { label = "K STAIR06", model = "cartty_hstairs01_k_stair06", price = 0 },
        { label = "K STAIR07", model = "cartty_hstairs01_k_stair07", price = 0 },
        { label = "K STAIR08", model = "cartty_hstairs01_k_stair08", price = 0 },
        { label = "K STAIR09", model = "cartty_hstairs01_k_stair09", price = 0 },
        { label = "K STAIR10", model = "cartty_hstairs01_k_stair10", price = 0 },
        { label = "K STAIR11", model = "cartty_hstairs01_k_stair11", price = 0 },
        { label = "K STAIR12", model = "cartty_hstairs01_k_stair12", price = 0 },
        -- Ls
        { label = "L STAIR03", model = "cartty_hstairs01_l_stair03", price = 0 },
        { label = "L STAIR04", model = "cartty_hstairs01_l_stair04", price = 0 },
        { label = "L STAIR05", model = "cartty_hstairs01_l_stair05", price = 0 },
        { label = "L STAIR06", model = "cartty_hstairs01_l_stair06", price = 0 },
        { label = "L STAIR07", model = "cartty_hstairs01_l_stair07", price = 0 },
        { label = "L STAIR08", model = "cartty_hstairs01_l_stair08", price = 0 },
        { label = "L STAIR09", model = "cartty_hstairs01_l_stair09", price = 0 },
        { label = "L STAIR10", model = "cartty_hstairs01_l_stair10", price = 0 },
        { label = "L STAIR11", model = "cartty_hstairs01_l_stair11", price = 0 },
        { label = "L STAIR12", model = "cartty_hstairs01_l_stair12", price = 0 },
        -- Ms
        { label = "M STAIR03", model = "cartty_hstairs01_m_stair03", price = 0 },
        { label = "M STAIR04", model = "cartty_hstairs01_m_stair04", price = 0 },
        { label = "M STAIR05", model = "cartty_hstairs01_m_stair05", price = 0 },
        { label = "M STAIR06", model = "cartty_hstairs01_m_stair06", price = 0 },
        { label = "M STAIR07", model = "cartty_hstairs01_m_stair07", price = 0 },
        { label = "M STAIR08", model = "cartty_hstairs01_m_stair08", price = 0 },
        { label = "M STAIR09", model = "cartty_hstairs01_m_stair09", price = 0 },
        { label = "M STAIR10", model = "cartty_hstairs01_m_stair10", price = 0 },
        { label = "M STAIR11", model = "cartty_hstairs01_m_stair11", price = 0 },
        { label = "M STAIR12", model = "cartty_hstairs01_m_stair12", price = 0 },
        -- Ns
        { label = "N STAIR03", model = "cartty_hstairs01_n_stair03", price = 0 },
        { label = "N STAIR04", model = "cartty_hstairs01_n_stair04", price = 0 },
        { label = "N STAIR05", model = "cartty_hstairs01_n_stair05", price = 0 },
        { label = "N STAIR06", model = "cartty_hstairs01_n_stair06", price = 0 },
        { label = "N STAIR07", model = "cartty_hstairs01_n_stair07", price = 0 },
        { label = "N STAIR08", model = "cartty_hstairs01_n_stair08", price = 0 },
        { label = "N STAIR09", model = "cartty_hstairs01_n_stair09", price = 0 },
        { label = "N STAIR10", model = "cartty_hstairs01_n_stair10", price = 0 },
        { label = "N STAIR11", model = "cartty_hstairs01_n_stair11", price = 0 },
        { label = "N STAIR12", model = "cartty_hstairs01_n_stair12", price = 0 },
        -- Os
        { label = "O STAIR03", model = "cartty_hstairs01_o_stair03", price = 0 },
        { label = "O STAIR04", model = "cartty_hstairs01_o_stair04", price = 0 },
        { label = "O STAIR05", model = "cartty_hstairs01_o_stair05", price = 0 },
        { label = "O STAIR06", model = "cartty_hstairs01_o_stair06", price = 0 },
        { label = "O STAIR07", model = "cartty_hstairs01_o_stair07", price = 0 },
        { label = "O STAIR08", model = "cartty_hstairs01_o_stair08", price = 0 },
        { label = "O STAIR09", model = "cartty_hstairs01_o_stair09", price = 0 },
        { label = "O STAIR10", model = "cartty_hstairs01_o_stair10", price = 0 },
        { label = "O STAIR11", model = "cartty_hstairs01_o_stair11", price = 0 },
        { label = "O STAIR12", model = "cartty_hstairs01_o_stair12", price = 0 },
        -- Ps
        { label = "P STAIR03", model = "cartty_hstairs01_p_stair03", price = 0 },
        { label = "P STAIR04", model = "cartty_hstairs01_p_stair04", price = 0 },
        { label = "P STAIR05", model = "cartty_hstairs01_p_stair05", price = 0 },
        { label = "P STAIR06", model = "cartty_hstairs01_p_stair06", price = 0 },
        { label = "P STAIR07", model = "cartty_hstairs01_p_stair07", price = 0 },
        { label = "P STAIR08", model = "cartty_hstairs01_p_stair08", price = 0 },
        { label = "P STAIR09", model = "cartty_hstairs01_p_stair09", price = 0 },
        { label = "P STAIR10", model = "cartty_hstairs01_p_stair10", price = 0 },
        { label = "P STAIR11", model = "cartty_hstairs01_p_stair11", price = 0 },
        { label = "P STAIR12", model = "cartty_hstairs01_p_stair12", price = 0 },
        -- Qs
        { label = "Q STAIR03", model = "cartty_hstairs01_q_stair03", price = 0 },
        { label = "Q STAIR04", model = "cartty_hstairs01_q_stair04", price = 0 },
        { label = "Q STAIR05", model = "cartty_hstairs01_q_stair05", price = 0 },
        { label = "Q STAIR06", model = "cartty_hstairs01_q_stair06", price = 0 },
        { label = "Q STAIR07", model = "cartty_hstairs01_q_stair07", price = 0 },
        { label = "Q STAIR08", model = "cartty_hstairs01_q_stair08", price = 0 },
        { label = "Q STAIR09", model = "cartty_hstairs01_q_stair09", price = 0 },
        { label = "Q STAIR10", model = "cartty_hstairs01_q_stair10", price = 0 },
        { label = "Q STAIR11", model = "cartty_hstairs01_q_stair11", price = 0 },
        { label = "Q STAIR12", model = "cartty_hstairs01_q_stair12", price = 0 },
        -- Rs
        { label = "R STAIR03", model = "cartty_hstairs01_r_stair03", price = 0 },
        { label = "R STAIR04", model = "cartty_hstairs01_r_stair04", price = 0 },
        { label = "R STAIR05", model = "cartty_hstairs01_r_stair05", price = 0 },
        { label = "R STAIR06", model = "cartty_hstairs01_r_stair06", price = 0 },
        { label = "R STAIR07", model = "cartty_hstairs01_r_stair07", price = 0 },
        { label = "R STAIR08", model = "cartty_hstairs01_r_stair08", price = 0 },
        { label = "R STAIR09", model = "cartty_hstairs01_r_stair09", price = 0 },
        { label = "R STAIR10", model = "cartty_hstairs01_r_stair10", price = 0 },
        { label = "R STAIR11", model = "cartty_hstairs01_r_stair11", price = 0 },
        { label = "R STAIR12", model = "cartty_hstairs01_r_stair12", price = 0 },
        -- Ss
        { label = "S STAIR03", model = "cartty_hstairs01_s_stair03", price = 0 },
        { label = "S STAIR04", model = "cartty_hstairs01_s_stair04", price = 0 },
        { label = "S STAIR05", model = "cartty_hstairs01_s_stair05", price = 0 },
        { label = "S STAIR06", model = "cartty_hstairs01_s_stair06", price = 0 },
        { label = "S STAIR07", model = "cartty_hstairs01_s_stair07", price = 0 },
        { label = "S STAIR08", model = "cartty_hstairs01_s_stair08", price = 0 },
        { label = "S STAIR09", model = "cartty_hstairs01_s_stair09", price = 0 },
        { label = "S STAIR10", model = "cartty_hstairs01_s_stair10", price = 0 },
        { label = "S STAIR11", model = "cartty_hstairs01_s_stair11", price = 0 },
        { label = "S STAIR12", model = "cartty_hstairs01_s_stair12", price = 0 },
        -- Ts
        { label = "T STAIR03", model = "cartty_hstairs01_t_stair03", price = 0 },
        { label = "T STAIR04", model = "cartty_hstairs01_t_stair04", price = 0 },
        { label = "T STAIR05", model = "cartty_hstairs01_t_stair05", price = 0 },
        { label = "T STAIR06", model = "cartty_hstairs01_t_stair06", price = 0 },
        { label = "T STAIR07", model = "cartty_hstairs01_t_stair07", price = 0 },
        { label = "T STAIR08", model = "cartty_hstairs01_t_stair08", price = 0 },
        { label = "T STAIR09", model = "cartty_hstairs01_t_stair09", price = 0 },
        { label = "T STAIR10", model = "cartty_hstairs01_t_stair10", price = 0 },
        { label = "T STAIR11", model = "cartty_hstairs01_t_stair11", price = 0 },
        { label = "T STAIR12", model = "cartty_hstairs01_t_stair12", price = 0 },
    }
}
