-- Cartty Store | Housing Stairs 01 | Ps-Housing
-- Docs: https://cartty.gitbook.io/cartty-docs/documentation/props/housing-stairs-01
-- Discord: https://discord.gg/4EXtjUjuKQ

{
    label = 'Stairs01',
    icon = 'fa-solid fa-utensils',
    items = {
        -- As
        { model = 'cartty_hstairs01_a_flat01', price = 0 },
        { model = 'cartty_hstairs01_a_flat02', price = 0 },
        { model = 'cartty_hstairs01_a_stair01', price = 0 },
        { model = 'cartty_hstairs01_a_stair02', price = 0 },
        { model = 'cartty_hstairs01_a_stair03', price = 0 },
        { model = 'cartty_hstairs01_a_stair04', price = 0 },
        { model = 'cartty_hstairs01_a_stair05', price = 0 },
        { model = 'cartty_hstairs01_a_stair06', price = 0 },
        { model = 'cartty_hstairs01_a_stair07', price = 0 },
        { model = 'cartty_hstairs01_a_stair08', price = 0 },
        { model = 'cartty_hstairs01_a_stair09', price = 0 },
        { model = 'cartty_hstairs01_a_stair10', price = 0 },
        { model = 'cartty_hstairs01_a_stair11', price = 0 },
        { model = 'cartty_hstairs01_a_stair12', price = 0 },
        -- Bs
        { model = 'cartty_hstairs01_b_flat01', price = 0 },
        { model = 'cartty_hstairs01_b_flat02', price = 0 },
        { model = 'cartty_hstairs01_b_stair01', price = 0 },
        { model = 'cartty_hstairs01_b_stair02', price = 0 },
        { model = 'cartty_hstairs01_b_stair03', price = 0 },
        { model = 'cartty_hstairs01_b_stair04', price = 0 },
        { model = 'cartty_hstairs01_b_stair05', price = 0 },
        { model = 'cartty_hstairs01_b_stair06', price = 0 },
        { model = 'cartty_hstairs01_b_stair07', price = 0 },
        { model = 'cartty_hstairs01_b_stair08', price = 0 },
        { model = 'cartty_hstairs01_b_stair09', price = 0 },
        { model = 'cartty_hstairs01_b_stair10', price = 0 },
        { model = 'cartty_hstairs01_b_stair11', price = 0 },
        { model = 'cartty_hstairs01_b_stair12', price = 0 },
        -- Cs
        { model = 'cartty_hstairs01_c_flat01', price = 0 },
        { model = 'cartty_hstairs01_c_flat02', price = 0 },
        { model = 'cartty_hstairs01_c_stair01', price = 0 },
        { model = 'cartty_hstairs01_c_stair02', price = 0 },
        { model = 'cartty_hstairs01_c_stair03', price = 0 },
        { model = 'cartty_hstairs01_c_stair04', price = 0 },
        { model = 'cartty_hstairs01_c_stair05', price = 0 },
        { model = 'cartty_hstairs01_c_stair06', price = 0 },
        { model = 'cartty_hstairs01_c_stair07', price = 0 },
        { model = 'cartty_hstairs01_c_stair08', price = 0 },
        { model = 'cartty_hstairs01_c_stair09', price = 0 },
        { model = 'cartty_hstairs01_c_stair10', price = 0 },
        { model = 'cartty_hstairs01_c_stair11', price = 0 },
        { model = 'cartty_hstairs01_c_stair12', price = 0 },
        -- Ds
        { model = 'cartty_hstairs01_d_flat01', price = 0 },
        { model = 'cartty_hstairs01_d_flat02', price = 0 },
        { model = 'cartty_hstairs01_d_stair01', price = 0 },
        { model = 'cartty_hstairs01_d_stair02', price = 0 },
        { model = 'cartty_hstairs01_d_stair03', price = 0 },
        { model = 'cartty_hstairs01_d_stair04', price = 0 },
        { model = 'cartty_hstairs01_d_stair05', price = 0 },
        { model = 'cartty_hstairs01_d_stair06', price = 0 },
        { model = 'cartty_hstairs01_d_stair07', price = 0 },
        { model = 'cartty_hstairs01_d_stair08', price = 0 },
        { model = 'cartty_hstairs01_d_stair09', price = 0 },
        { model = 'cartty_hstairs01_d_stair10', price = 0 },
        { model = 'cartty_hstairs01_d_stair11', price = 0 },
        { model = 'cartty_hstairs01_d_stair12', price = 0 },
        -- Es
        { model = 'cartty_hstairs01_e_flat01', price = 0 },
        { model = 'cartty_hstairs01_e_flat02', price = 0 },
        { model = 'cartty_hstairs01_e_stair01', price = 0 },
        { model = 'cartty_hstairs01_e_stair02', price = 0 },
        { model = 'cartty_hstairs01_e_stair03', price = 0 },
        { model = 'cartty_hstairs01_e_stair04', price = 0 },
        { model = 'cartty_hstairs01_e_stair05', price = 0 },
        { model = 'cartty_hstairs01_e_stair06', price = 0 },
        { model = 'cartty_hstairs01_e_stair07', price = 0 },
        { model = 'cartty_hstairs01_e_stair08', price = 0 },
        { model = 'cartty_hstairs01_e_stair09', price = 0 },
        { model = 'cartty_hstairs01_e_stair10', price = 0 },
        { model = 'cartty_hstairs01_e_stair11', price = 0 },
        { model = 'cartty_hstairs01_e_stair12', price = 0 },
        -- Fs
        { model = 'cartty_hstairs01_f_stair03', price = 0 },
        { model = 'cartty_hstairs01_f_stair04', price = 0 },
        { model = 'cartty_hstairs01_f_stair05', price = 0 },
        { model = 'cartty_hstairs01_f_stair06', price = 0 },
        { model = 'cartty_hstairs01_f_stair07', price = 0 },
        { model = 'cartty_hstairs01_f_stair08', price = 0 },
        { model = 'cartty_hstairs01_f_stair09', price = 0 },
        { model = 'cartty_hstairs01_f_stair10', price = 0 },
        { model = 'cartty_hstairs01_f_stair11', price = 0 },
        { model = 'cartty_hstairs01_f_stair12', price = 0 },
        -- Gs
        { model = 'cartty_hstairs01_g_stair03', price = 0 },
        { model = 'cartty_hstairs01_g_stair04', price = 0 },
        { model = 'cartty_hstairs01_g_stair05', price = 0 },
        { model = 'cartty_hstairs01_g_stair06', price = 0 },
        { model = 'cartty_hstairs01_g_stair07', price = 0 },
        { model = 'cartty_hstairs01_g_stair08', price = 0 },
        { model = 'cartty_hstairs01_g_stair09', price = 0 },
        { model = 'cartty_hstairs01_g_stair10', price = 0 },
        { model = 'cartty_hstairs01_g_stair11', price = 0 },
        { model = 'cartty_hstairs01_g_stair12', price = 0 },
        -- Hs
        { model = 'cartty_hstairs01_h_stair03', price = 0 },
        { model = 'cartty_hstairs01_h_stair04', price = 0 },
        { model = 'cartty_hstairs01_h_stair05', price = 0 },
        { model = 'cartty_hstairs01_h_stair06', price = 0 },
        { model = 'cartty_hstairs01_h_stair07', price = 0 },
        { model = 'cartty_hstairs01_h_stair08', price = 0 },
        { model = 'cartty_hstairs01_h_stair09', price = 0 },
        { model = 'cartty_hstairs01_h_stair10', price = 0 },
        { model = 'cartty_hstairs01_h_stair11', price = 0 },
        { model = 'cartty_hstairs01_h_stair12', price = 0 },
        -- Is
        { model = 'cartty_hstairs01_i_stair03', price = 0 },
        { model = 'cartty_hstairs01_i_stair04', price = 0 },
        { model = 'cartty_hstairs01_i_stair05', price = 0 },
        { model = 'cartty_hstairs01_i_stair06', price = 0 },
        { model = 'cartty_hstairs01_i_stair07', price = 0 },
        { model = 'cartty_hstairs01_i_stair08', price = 0 },
        { model = 'cartty_hstairs01_i_stair09', price = 0 },
        { model = 'cartty_hstairs01_i_stair10', price = 0 },
        { model = 'cartty_hstairs01_i_stair11', price = 0 },
        { model = 'cartty_hstairs01_i_stair12', price = 0 },
        -- Js
        { model = 'cartty_hstairs01_j_stair03', price = 0 },
        { model = 'cartty_hstairs01_j_stair04', price = 0 },
        { model = 'cartty_hstairs01_j_stair05', price = 0 },
        { model = 'cartty_hstairs01_j_stair06', price = 0 },
        { model = 'cartty_hstairs01_j_stair07', price = 0 },
        { model = 'cartty_hstairs01_j_stair08', price = 0 },
        { model = 'cartty_hstairs01_j_stair09', price = 0 },
        { model = 'cartty_hstairs01_j_stair10', price = 0 },
        { model = 'cartty_hstairs01_j_stair11', price = 0 },
        { model = 'cartty_hstairs01_j_stair12', price = 0 },
        -- Ks
        { model = 'cartty_hstairs01_k_stair03', price = 0 },
        { model = 'cartty_hstairs01_k_stair04', price = 0 },
        { model = 'cartty_hstairs01_k_stair05', price = 0 },
        { model = 'cartty_hstairs01_k_stair06', price = 0 },
        { model = 'cartty_hstairs01_k_stair07', price = 0 },
        { model = 'cartty_hstairs01_k_stair08', price = 0 },
        { model = 'cartty_hstairs01_k_stair09', price = 0 },
        { model = 'cartty_hstairs01_k_stair10', price = 0 },
        { model = 'cartty_hstairs01_k_stair11', price = 0 },
        { model = 'cartty_hstairs01_k_stair12', price = 0 },
        -- Ls
        { model = 'cartty_hstairs01_l_stair03', price = 0 },
        { model = 'cartty_hstairs01_l_stair04', price = 0 },
        { model = 'cartty_hstairs01_l_stair05', price = 0 },
        { model = 'cartty_hstairs01_l_stair06', price = 0 },
        { model = 'cartty_hstairs01_l_stair07', price = 0 },
        { model = 'cartty_hstairs01_l_stair08', price = 0 },
        { model = 'cartty_hstairs01_l_stair09', price = 0 },
        { model = 'cartty_hstairs01_l_stair10', price = 0 },
        { model = 'cartty_hstairs01_l_stair11', price = 0 },
        { model = 'cartty_hstairs01_l_stair12', price = 0 },
        -- Ms
        { model = 'cartty_hstairs01_m_stair03', price = 0 },
        { model = 'cartty_hstairs01_m_stair04', price = 0 },
        { model = 'cartty_hstairs01_m_stair05', price = 0 },
        { model = 'cartty_hstairs01_m_stair06', price = 0 },
        { model = 'cartty_hstairs01_m_stair07', price = 0 },
        { model = 'cartty_hstairs01_m_stair08', price = 0 },
        { model = 'cartty_hstairs01_m_stair09', price = 0 },
        { model = 'cartty_hstairs01_m_stair10', price = 0 },
        { model = 'cartty_hstairs01_m_stair11', price = 0 },
        { model = 'cartty_hstairs01_m_stair12', price = 0 },
        -- Ns
        { model = 'cartty_hstairs01_n_stair03', price = 0 },
        { model = 'cartty_hstairs01_n_stair04', price = 0 },
        { model = 'cartty_hstairs01_n_stair05', price = 0 },
        { model = 'cartty_hstairs01_n_stair06', price = 0 },
        { model = 'cartty_hstairs01_n_stair07', price = 0 },
        { model = 'cartty_hstairs01_n_stair08', price = 0 },
        { model = 'cartty_hstairs01_n_stair09', price = 0 },
        { model = 'cartty_hstairs01_n_stair10', price = 0 },
        { model = 'cartty_hstairs01_n_stair11', price = 0 },
        { model = 'cartty_hstairs01_n_stair12', price = 0 },
        -- Os
        { model = 'cartty_hstairs01_o_stair03', price = 0 },
        { model = 'cartty_hstairs01_o_stair04', price = 0 },
        { model = 'cartty_hstairs01_o_stair05', price = 0 },
        { model = 'cartty_hstairs01_o_stair06', price = 0 },
        { model = 'cartty_hstairs01_o_stair07', price = 0 },
        { model = 'cartty_hstairs01_o_stair08', price = 0 },
        { model = 'cartty_hstairs01_o_stair09', price = 0 },
        { model = 'cartty_hstairs01_o_stair10', price = 0 },
        { model = 'cartty_hstairs01_o_stair11', price = 0 },
        { model = 'cartty_hstairs01_o_stair12', price = 0 },
        -- Ps
        { model = 'cartty_hstairs01_p_stair03', price = 0 },
        { model = 'cartty_hstairs01_p_stair04', price = 0 },
        { model = 'cartty_hstairs01_p_stair05', price = 0 },
        { model = 'cartty_hstairs01_p_stair06', price = 0 },
        { model = 'cartty_hstairs01_p_stair07', price = 0 },
        { model = 'cartty_hstairs01_p_stair08', price = 0 },
        { model = 'cartty_hstairs01_p_stair09', price = 0 },
        { model = 'cartty_hstairs01_p_stair10', price = 0 },
        { model = 'cartty_hstairs01_p_stair11', price = 0 },
        { model = 'cartty_hstairs01_p_stair12', price = 0 },
        -- Qs
        { model = 'cartty_hstairs01_q_stair03', price = 0 },
        { model = 'cartty_hstairs01_q_stair04', price = 0 },
        { model = 'cartty_hstairs01_q_stair05', price = 0 },
        { model = 'cartty_hstairs01_q_stair06', price = 0 },
        { model = 'cartty_hstairs01_q_stair07', price = 0 },
        { model = 'cartty_hstairs01_q_stair08', price = 0 },
        { model = 'cartty_hstairs01_q_stair09', price = 0 },
        { model = 'cartty_hstairs01_q_stair10', price = 0 },
        { model = 'cartty_hstairs01_q_stair11', price = 0 },
        { model = 'cartty_hstairs01_q_stair12', price = 0 },
        -- Rs
        { model = 'cartty_hstairs01_r_stair03', price = 0 },
        { model = 'cartty_hstairs01_r_stair04', price = 0 },
        { model = 'cartty_hstairs01_r_stair05', price = 0 },
        { model = 'cartty_hstairs01_r_stair06', price = 0 },
        { model = 'cartty_hstairs01_r_stair07', price = 0 },
        { model = 'cartty_hstairs01_r_stair08', price = 0 },
        { model = 'cartty_hstairs01_r_stair09', price = 0 },
        { model = 'cartty_hstairs01_r_stair10', price = 0 },
        { model = 'cartty_hstairs01_r_stair11', price = 0 },
        { model = 'cartty_hstairs01_r_stair12', price = 0 },
        -- Ss
        { model = 'cartty_hstairs01_s_stair03', price = 0 },
        { model = 'cartty_hstairs01_s_stair04', price = 0 },
        { model = 'cartty_hstairs01_s_stair05', price = 0 },
        { model = 'cartty_hstairs01_s_stair06', price = 0 },
        { model = 'cartty_hstairs01_s_stair07', price = 0 },
        { model = 'cartty_hstairs01_s_stair08', price = 0 },
        { model = 'cartty_hstairs01_s_stair09', price = 0 },
        { model = 'cartty_hstairs01_s_stair10', price = 0 },
        { model = 'cartty_hstairs01_s_stair11', price = 0 },
        { model = 'cartty_hstairs01_s_stair12', price = 0 },
        -- Ts
        { model = 'cartty_hstairs01_t_stair03', price = 0 },
        { model = 'cartty_hstairs01_t_stair04', price = 0 },
        { model = 'cartty_hstairs01_t_stair05', price = 0 },
        { model = 'cartty_hstairs01_t_stair06', price = 0 },
        { model = 'cartty_hstairs01_t_stair07', price = 0 },
        { model = 'cartty_hstairs01_t_stair08', price = 0 },
        { model = 'cartty_hstairs01_t_stair09', price = 0 },
        { model = 'cartty_hstairs01_t_stair10', price = 0 },
        { model = 'cartty_hstairs01_t_stair11', price = 0 },
        { model = 'cartty_hstairs01_t_stair12', price = 0 },
    }
}
