-- Cartty Store | Housing Stairs 01 | qb-housing
-- Docs: https://cartty.gitbook.io/cartty-docs/documentation/props/housing-stairs-01
-- Discord: https://discord.gg/4EXtjUjuKQ

["stairs01"] = {
    label = "Stairs01",
    items = {
        -- As
        [1]   = { ["object"] = "cartty_hstairs01_a_flat01", ["price"] = 0, ["label"] = "A FLAT01" },
        [2]   = { ["object"] = "cartty_hstairs01_a_flat02", ["price"] = 0, ["label"] = "A FLAT02" },
        [3]   = { ["object"] = "cartty_hstairs01_a_stair01", ["price"] = 0, ["label"] = "A STAIR01" },
        [4]   = { ["object"] = "cartty_hstairs01_a_stair02", ["price"] = 0, ["label"] = "A STAIR02" },
        [5]   = { ["object"] = "cartty_hstairs01_a_stair03", ["price"] = 0, ["label"] = "A STAIR03" },
        [6]   = { ["object"] = "cartty_hstairs01_a_stair04", ["price"] = 0, ["label"] = "A STAIR04" },
        [7]   = { ["object"] = "cartty_hstairs01_a_stair05", ["price"] = 0, ["label"] = "A STAIR05" },
        [8]   = { ["object"] = "cartty_hstairs01_a_stair06", ["price"] = 0, ["label"] = "A STAIR06" },
        [9]   = { ["object"] = "cartty_hstairs01_a_stair07", ["price"] = 0, ["label"] = "A STAIR07" },
        [10]  = { ["object"] = "cartty_hstairs01_a_stair08", ["price"] = 0, ["label"] = "A STAIR08" },
        [11]  = { ["object"] = "cartty_hstairs01_a_stair09", ["price"] = 0, ["label"] = "A STAIR09" },
        [12]  = { ["object"] = "cartty_hstairs01_a_stair10", ["price"] = 0, ["label"] = "A STAIR10" },
        [13]  = { ["object"] = "cartty_hstairs01_a_stair11", ["price"] = 0, ["label"] = "A STAIR11" },
        [14]  = { ["object"] = "cartty_hstairs01_a_stair12", ["price"] = 0, ["label"] = "A STAIR12" },
        -- Bs
        [15]  = { ["object"] = "cartty_hstairs01_b_flat01", ["price"] = 0, ["label"] = "B FLAT01" },
        [16]  = { ["object"] = "cartty_hstairs01_b_flat02", ["price"] = 0, ["label"] = "B FLAT02" },
        [17]  = { ["object"] = "cartty_hstairs01_b_stair01", ["price"] = 0, ["label"] = "B STAIR01" },
        [18]  = { ["object"] = "cartty_hstairs01_b_stair02", ["price"] = 0, ["label"] = "B STAIR02" },
        [19]  = { ["object"] = "cartty_hstairs01_b_stair03", ["price"] = 0, ["label"] = "B STAIR03" },
        [20]  = { ["object"] = "cartty_hstairs01_b_stair04", ["price"] = 0, ["label"] = "B STAIR04" },
        [21]  = { ["object"] = "cartty_hstairs01_b_stair05", ["price"] = 0, ["label"] = "B STAIR05" },
        [22]  = { ["object"] = "cartty_hstairs01_b_stair06", ["price"] = 0, ["label"] = "B STAIR06" },
        [23]  = { ["object"] = "cartty_hstairs01_b_stair07", ["price"] = 0, ["label"] = "B STAIR07" },
        [24]  = { ["object"] = "cartty_hstairs01_b_stair08", ["price"] = 0, ["label"] = "B STAIR08" },
        [25]  = { ["object"] = "cartty_hstairs01_b_stair09", ["price"] = 0, ["label"] = "B STAIR09" },
        [26]  = { ["object"] = "cartty_hstairs01_b_stair10", ["price"] = 0, ["label"] = "B STAIR10" },
        [27]  = { ["object"] = "cartty_hstairs01_b_stair11", ["price"] = 0, ["label"] = "B STAIR11" },
        [28]  = { ["object"] = "cartty_hstairs01_b_stair12", ["price"] = 0, ["label"] = "B STAIR12" },
        -- Cs
        [29]  = { ["object"] = "cartty_hstairs01_c_flat01", ["price"] = 0, ["label"] = "C FLAT01" },
        [30]  = { ["object"] = "cartty_hstairs01_c_flat02", ["price"] = 0, ["label"] = "C FLAT02" },
        [31]  = { ["object"] = "cartty_hstairs01_c_stair01", ["price"] = 0, ["label"] = "C STAIR01" },
        [32]  = { ["object"] = "cartty_hstairs01_c_stair02", ["price"] = 0, ["label"] = "C STAIR02" },
        [33]  = { ["object"] = "cartty_hstairs01_c_stair03", ["price"] = 0, ["label"] = "C STAIR03" },
        [34]  = { ["object"] = "cartty_hstairs01_c_stair04", ["price"] = 0, ["label"] = "C STAIR04" },
        [35]  = { ["object"] = "cartty_hstairs01_c_stair05", ["price"] = 0, ["label"] = "C STAIR05" },
        [36]  = { ["object"] = "cartty_hstairs01_c_stair06", ["price"] = 0, ["label"] = "C STAIR06" },
        [37]  = { ["object"] = "cartty_hstairs01_c_stair07", ["price"] = 0, ["label"] = "C STAIR07" },
        [38]  = { ["object"] = "cartty_hstairs01_c_stair08", ["price"] = 0, ["label"] = "C STAIR08" },
        [39]  = { ["object"] = "cartty_hstairs01_c_stair09", ["price"] = 0, ["label"] = "C STAIR09" },
        [40]  = { ["object"] = "cartty_hstairs01_c_stair10", ["price"] = 0, ["label"] = "C STAIR10" },
        [41]  = { ["object"] = "cartty_hstairs01_c_stair11", ["price"] = 0, ["label"] = "C STAIR11" },
        [42]  = { ["object"] = "cartty_hstairs01_c_stair12", ["price"] = 0, ["label"] = "C STAIR12" },
        -- Ds
        [43]  = { ["object"] = "cartty_hstairs01_d_flat01", ["price"] = 0, ["label"] = "D FLAT01" },
        [44]  = { ["object"] = "cartty_hstairs01_d_flat02", ["price"] = 0, ["label"] = "D FLAT02" },
        [45]  = { ["object"] = "cartty_hstairs01_d_stair01", ["price"] = 0, ["label"] = "D STAIR01" },
        [46]  = { ["object"] = "cartty_hstairs01_d_stair02", ["price"] = 0, ["label"] = "D STAIR02" },
        [47]  = { ["object"] = "cartty_hstairs01_d_stair03", ["price"] = 0, ["label"] = "D STAIR03" },
        [48]  = { ["object"] = "cartty_hstairs01_d_stair04", ["price"] = 0, ["label"] = "D STAIR04" },
        [49]  = { ["object"] = "cartty_hstairs01_d_stair05", ["price"] = 0, ["label"] = "D STAIR05" },
        [50]  = { ["object"] = "cartty_hstairs01_d_stair06", ["price"] = 0, ["label"] = "D STAIR06" },
        [51]  = { ["object"] = "cartty_hstairs01_d_stair07", ["price"] = 0, ["label"] = "D STAIR07" },
        [52]  = { ["object"] = "cartty_hstairs01_d_stair08", ["price"] = 0, ["label"] = "D STAIR08" },
        [53]  = { ["object"] = "cartty_hstairs01_d_stair09", ["price"] = 0, ["label"] = "D STAIR09" },
        [54]  = { ["object"] = "cartty_hstairs01_d_stair10", ["price"] = 0, ["label"] = "D STAIR10" },
        [55]  = { ["object"] = "cartty_hstairs01_d_stair11", ["price"] = 0, ["label"] = "D STAIR11" },
        [56]  = { ["object"] = "cartty_hstairs01_d_stair12", ["price"] = 0, ["label"] = "D STAIR12" },
        -- Es
        [57]  = { ["object"] = "cartty_hstairs01_e_flat01", ["price"] = 0, ["label"] = "E FLAT01" },
        [58]  = { ["object"] = "cartty_hstairs01_e_flat02", ["price"] = 0, ["label"] = "E FLAT02" },
        [59]  = { ["object"] = "cartty_hstairs01_e_stair01", ["price"] = 0, ["label"] = "E STAIR01" },
        [60]  = { ["object"] = "cartty_hstairs01_e_stair02", ["price"] = 0, ["label"] = "E STAIR02" },
        [61]  = { ["object"] = "cartty_hstairs01_e_stair03", ["price"] = 0, ["label"] = "E STAIR03" },
        [62]  = { ["object"] = "cartty_hstairs01_e_stair04", ["price"] = 0, ["label"] = "E STAIR04" },
        [63]  = { ["object"] = "cartty_hstairs01_e_stair05", ["price"] = 0, ["label"] = "E STAIR05" },
        [64]  = { ["object"] = "cartty_hstairs01_e_stair06", ["price"] = 0, ["label"] = "E STAIR06" },
        [65]  = { ["object"] = "cartty_hstairs01_e_stair07", ["price"] = 0, ["label"] = "E STAIR07" },
        [66]  = { ["object"] = "cartty_hstairs01_e_stair08", ["price"] = 0, ["label"] = "E STAIR08" },
        [67]  = { ["object"] = "cartty_hstairs01_e_stair09", ["price"] = 0, ["label"] = "E STAIR09" },
        [68]  = { ["object"] = "cartty_hstairs01_e_stair10", ["price"] = 0, ["label"] = "E STAIR10" },
        [69]  = { ["object"] = "cartty_hstairs01_e_stair11", ["price"] = 0, ["label"] = "E STAIR11" },
        [70]  = { ["object"] = "cartty_hstairs01_e_stair12", ["price"] = 0, ["label"] = "E STAIR12" },
        -- Fs
        [71]  = { ["object"] = "cartty_hstairs01_f_stair03", ["price"] = 0, ["label"] = "F STAIR03" },
        [72]  = { ["object"] = "cartty_hstairs01_f_stair04", ["price"] = 0, ["label"] = "F STAIR04" },
        [73]  = { ["object"] = "cartty_hstairs01_f_stair05", ["price"] = 0, ["label"] = "F STAIR05" },
        [74]  = { ["object"] = "cartty_hstairs01_f_stair06", ["price"] = 0, ["label"] = "F STAIR06" },
        [75]  = { ["object"] = "cartty_hstairs01_f_stair07", ["price"] = 0, ["label"] = "F STAIR07" },
        [76]  = { ["object"] = "cartty_hstairs01_f_stair08", ["price"] = 0, ["label"] = "F STAIR08" },
        [77]  = { ["object"] = "cartty_hstairs01_f_stair09", ["price"] = 0, ["label"] = "F STAIR09" },
        [78]  = { ["object"] = "cartty_hstairs01_f_stair10", ["price"] = 0, ["label"] = "F STAIR10" },
        [79]  = { ["object"] = "cartty_hstairs01_f_stair11", ["price"] = 0, ["label"] = "F STAIR11" },
        [80]  = { ["object"] = "cartty_hstairs01_f_stair12", ["price"] = 0, ["label"] = "F STAIR12" },
        -- Gs
        [81]  = { ["object"] = "cartty_hstairs01_g_stair03", ["price"] = 0, ["label"] = "G STAIR03" },
        [82]  = { ["object"] = "cartty_hstairs01_g_stair04", ["price"] = 0, ["label"] = "G STAIR04" },
        [83]  = { ["object"] = "cartty_hstairs01_g_stair05", ["price"] = 0, ["label"] = "G STAIR05" },
        [84]  = { ["object"] = "cartty_hstairs01_g_stair06", ["price"] = 0, ["label"] = "G STAIR06" },
        [85]  = { ["object"] = "cartty_hstairs01_g_stair07", ["price"] = 0, ["label"] = "G STAIR07" },
        [86]  = { ["object"] = "cartty_hstairs01_g_stair08", ["price"] = 0, ["label"] = "G STAIR08" },
        [87]  = { ["object"] = "cartty_hstairs01_g_stair09", ["price"] = 0, ["label"] = "G STAIR09" },
        [88]  = { ["object"] = "cartty_hstairs01_g_stair10", ["price"] = 0, ["label"] = "G STAIR10" },
        [89]  = { ["object"] = "cartty_hstairs01_g_stair11", ["price"] = 0, ["label"] = "G STAIR11" },
        [90]  = { ["object"] = "cartty_hstairs01_g_stair12", ["price"] = 0, ["label"] = "G STAIR12" },
        -- Hs
        [91]  = { ["object"] = "cartty_hstairs01_h_stair03", ["price"] = 0, ["label"] = "H STAIR03" },
        [92]  = { ["object"] = "cartty_hstairs01_h_stair04", ["price"] = 0, ["label"] = "H STAIR04" },
        [93]  = { ["object"] = "cartty_hstairs01_h_stair05", ["price"] = 0, ["label"] = "H STAIR05" },
        [94]  = { ["object"] = "cartty_hstairs01_h_stair06", ["price"] = 0, ["label"] = "H STAIR06" },
        [95]  = { ["object"] = "cartty_hstairs01_h_stair07", ["price"] = 0, ["label"] = "H STAIR07" },
        [96]  = { ["object"] = "cartty_hstairs01_h_stair08", ["price"] = 0, ["label"] = "H STAIR08" },
        [97]  = { ["object"] = "cartty_hstairs01_h_stair09", ["price"] = 0, ["label"] = "H STAIR09" },
        [98]  = { ["object"] = "cartty_hstairs01_h_stair10", ["price"] = 0, ["label"] = "H STAIR10" },
        [99]  = { ["object"] = "cartty_hstairs01_h_stair11", ["price"] = 0, ["label"] = "H STAIR11" },
        [100] = { ["object"] = "cartty_hstairs01_h_stair12", ["price"] = 0, ["label"] = "H STAIR12" },
        -- Is
        [101] = { ["object"] = "cartty_hstairs01_i_stair03", ["price"] = 0, ["label"] = "I STAIR03" },
        [102] = { ["object"] = "cartty_hstairs01_i_stair04", ["price"] = 0, ["label"] = "I STAIR04" },
        [103] = { ["object"] = "cartty_hstairs01_i_stair05", ["price"] = 0, ["label"] = "I STAIR05" },
        [104] = { ["object"] = "cartty_hstairs01_i_stair06", ["price"] = 0, ["label"] = "I STAIR06" },
        [105] = { ["object"] = "cartty_hstairs01_i_stair07", ["price"] = 0, ["label"] = "I STAIR07" },
        [106] = { ["object"] = "cartty_hstairs01_i_stair08", ["price"] = 0, ["label"] = "I STAIR08" },
        [107] = { ["object"] = "cartty_hstairs01_i_stair09", ["price"] = 0, ["label"] = "I STAIR09" },
        [108] = { ["object"] = "cartty_hstairs01_i_stair10", ["price"] = 0, ["label"] = "I STAIR10" },
        [109] = { ["object"] = "cartty_hstairs01_i_stair11", ["price"] = 0, ["label"] = "I STAIR11" },
        [110] = { ["object"] = "cartty_hstairs01_i_stair12", ["price"] = 0, ["label"] = "I STAIR12" },
        -- Js
        [111] = { ["object"] = "cartty_hstairs01_j_stair03", ["price"] = 0, ["label"] = "J STAIR03" },
        [112] = { ["object"] = "cartty_hstairs01_j_stair04", ["price"] = 0, ["label"] = "J STAIR04" },
        [113] = { ["object"] = "cartty_hstairs01_j_stair05", ["price"] = 0, ["label"] = "J STAIR05" },
        [114] = { ["object"] = "cartty_hstairs01_j_stair06", ["price"] = 0, ["label"] = "J STAIR06" },
        [115] = { ["object"] = "cartty_hstairs01_j_stair07", ["price"] = 0, ["label"] = "J STAIR07" },
        [116] = { ["object"] = "cartty_hstairs01_j_stair08", ["price"] = 0, ["label"] = "J STAIR08" },
        [117] = { ["object"] = "cartty_hstairs01_j_stair09", ["price"] = 0, ["label"] = "J STAIR09" },
        [118] = { ["object"] = "cartty_hstairs01_j_stair10", ["price"] = 0, ["label"] = "J STAIR10" },
        [119] = { ["object"] = "cartty_hstairs01_j_stair11", ["price"] = 0, ["label"] = "J STAIR11" },
        [120] = { ["object"] = "cartty_hstairs01_j_stair12", ["price"] = 0, ["label"] = "J STAIR12" },
        -- Ks
        [121] = { ["object"] = "cartty_hstairs01_k_stair03", ["price"] = 0, ["label"] = "K STAIR03" },
        [122] = { ["object"] = "cartty_hstairs01_k_stair04", ["price"] = 0, ["label"] = "K STAIR04" },
        [123] = { ["object"] = "cartty_hstairs01_k_stair05", ["price"] = 0, ["label"] = "K STAIR05" },
        [124] = { ["object"] = "cartty_hstairs01_k_stair06", ["price"] = 0, ["label"] = "K STAIR06" },
        [125] = { ["object"] = "cartty_hstairs01_k_stair07", ["price"] = 0, ["label"] = "K STAIR07" },
        [126] = { ["object"] = "cartty_hstairs01_k_stair08", ["price"] = 0, ["label"] = "K STAIR08" },
        [127] = { ["object"] = "cartty_hstairs01_k_stair09", ["price"] = 0, ["label"] = "K STAIR09" },
        [128] = { ["object"] = "cartty_hstairs01_k_stair10", ["price"] = 0, ["label"] = "K STAIR10" },
        [129] = { ["object"] = "cartty_hstairs01_k_stair11", ["price"] = 0, ["label"] = "K STAIR11" },
        [130] = { ["object"] = "cartty_hstairs01_k_stair12", ["price"] = 0, ["label"] = "K STAIR12" },
        -- Ls
        [131] = { ["object"] = "cartty_hstairs01_l_stair03", ["price"] = 0, ["label"] = "L STAIR03" },
        [132] = { ["object"] = "cartty_hstairs01_l_stair04", ["price"] = 0, ["label"] = "L STAIR04" },
        [133] = { ["object"] = "cartty_hstairs01_l_stair05", ["price"] = 0, ["label"] = "L STAIR05" },
        [134] = { ["object"] = "cartty_hstairs01_l_stair06", ["price"] = 0, ["label"] = "L STAIR06" },
        [135] = { ["object"] = "cartty_hstairs01_l_stair07", ["price"] = 0, ["label"] = "L STAIR07" },
        [136] = { ["object"] = "cartty_hstairs01_l_stair08", ["price"] = 0, ["label"] = "L STAIR08" },
        [137] = { ["object"] = "cartty_hstairs01_l_stair09", ["price"] = 0, ["label"] = "L STAIR09" },
        [138] = { ["object"] = "cartty_hstairs01_l_stair10", ["price"] = 0, ["label"] = "L STAIR10" },
        [139] = { ["object"] = "cartty_hstairs01_l_stair11", ["price"] = 0, ["label"] = "L STAIR11" },
        [140] = { ["object"] = "cartty_hstairs01_l_stair12", ["price"] = 0, ["label"] = "L STAIR12" },
        -- Ms
        [141] = { ["object"] = "cartty_hstairs01_m_stair03", ["price"] = 0, ["label"] = "M STAIR03" },
        [142] = { ["object"] = "cartty_hstairs01_m_stair04", ["price"] = 0, ["label"] = "M STAIR04" },
        [143] = { ["object"] = "cartty_hstairs01_m_stair05", ["price"] = 0, ["label"] = "M STAIR05" },
        [144] = { ["object"] = "cartty_hstairs01_m_stair06", ["price"] = 0, ["label"] = "M STAIR06" },
        [145] = { ["object"] = "cartty_hstairs01_m_stair07", ["price"] = 0, ["label"] = "M STAIR07" },
        [146] = { ["object"] = "cartty_hstairs01_m_stair08", ["price"] = 0, ["label"] = "M STAIR08" },
        [147] = { ["object"] = "cartty_hstairs01_m_stair09", ["price"] = 0, ["label"] = "M STAIR09" },
        [148] = { ["object"] = "cartty_hstairs01_m_stair10", ["price"] = 0, ["label"] = "M STAIR10" },
        [149] = { ["object"] = "cartty_hstairs01_m_stair11", ["price"] = 0, ["label"] = "M STAIR11" },
        [150] = { ["object"] = "cartty_hstairs01_m_stair12", ["price"] = 0, ["label"] = "M STAIR12" },
        -- Ns
        [151] = { ["object"] = "cartty_hstairs01_n_stair03", ["price"] = 0, ["label"] = "N STAIR03" },
        [152] = { ["object"] = "cartty_hstairs01_n_stair04", ["price"] = 0, ["label"] = "N STAIR04" },
        [153] = { ["object"] = "cartty_hstairs01_n_stair05", ["price"] = 0, ["label"] = "N STAIR05" },
        [154] = { ["object"] = "cartty_hstairs01_n_stair06", ["price"] = 0, ["label"] = "N STAIR06" },
        [155] = { ["object"] = "cartty_hstairs01_n_stair07", ["price"] = 0, ["label"] = "N STAIR07" },
        [156] = { ["object"] = "cartty_hstairs01_n_stair08", ["price"] = 0, ["label"] = "N STAIR08" },
        [157] = { ["object"] = "cartty_hstairs01_n_stair09", ["price"] = 0, ["label"] = "N STAIR09" },
        [158] = { ["object"] = "cartty_hstairs01_n_stair10", ["price"] = 0, ["label"] = "N STAIR10" },
        [159] = { ["object"] = "cartty_hstairs01_n_stair11", ["price"] = 0, ["label"] = "N STAIR11" },
        [160] = { ["object"] = "cartty_hstairs01_n_stair12", ["price"] = 0, ["label"] = "N STAIR12" },
        -- Os
        [161] = { ["object"] = "cartty_hstairs01_o_stair03", ["price"] = 0, ["label"] = "O STAIR03" },
        [162] = { ["object"] = "cartty_hstairs01_o_stair04", ["price"] = 0, ["label"] = "O STAIR04" },
        [163] = { ["object"] = "cartty_hstairs01_o_stair05", ["price"] = 0, ["label"] = "O STAIR05" },
        [164] = { ["object"] = "cartty_hstairs01_o_stair06", ["price"] = 0, ["label"] = "O STAIR06" },
        [165] = { ["object"] = "cartty_hstairs01_o_stair07", ["price"] = 0, ["label"] = "O STAIR07" },
        [166] = { ["object"] = "cartty_hstairs01_o_stair08", ["price"] = 0, ["label"] = "O STAIR08" },
        [167] = { ["object"] = "cartty_hstairs01_o_stair09", ["price"] = 0, ["label"] = "O STAIR09" },
        [168] = { ["object"] = "cartty_hstairs01_o_stair10", ["price"] = 0, ["label"] = "O STAIR10" },
        [169] = { ["object"] = "cartty_hstairs01_o_stair11", ["price"] = 0, ["label"] = "O STAIR11" },
        [170] = { ["object"] = "cartty_hstairs01_o_stair12", ["price"] = 0, ["label"] = "O STAIR12" },
        -- Ps
        [171] = { ["object"] = "cartty_hstairs01_p_stair03", ["price"] = 0, ["label"] = "P STAIR03" },
        [172] = { ["object"] = "cartty_hstairs01_p_stair04", ["price"] = 0, ["label"] = "P STAIR04" },
        [173] = { ["object"] = "cartty_hstairs01_p_stair05", ["price"] = 0, ["label"] = "P STAIR05" },
        [174] = { ["object"] = "cartty_hstairs01_p_stair06", ["price"] = 0, ["label"] = "P STAIR06" },
        [175] = { ["object"] = "cartty_hstairs01_p_stair07", ["price"] = 0, ["label"] = "P STAIR07" },
        [176] = { ["object"] = "cartty_hstairs01_p_stair08", ["price"] = 0, ["label"] = "P STAIR08" },
        [177] = { ["object"] = "cartty_hstairs01_p_stair09", ["price"] = 0, ["label"] = "P STAIR09" },
        [178] = { ["object"] = "cartty_hstairs01_p_stair10", ["price"] = 0, ["label"] = "P STAIR10" },
        [179] = { ["object"] = "cartty_hstairs01_p_stair11", ["price"] = 0, ["label"] = "P STAIR11" },
        [180] = { ["object"] = "cartty_hstairs01_p_stair12", ["price"] = 0, ["label"] = "P STAIR12" },
        -- Qs
        [181] = { ["object"] = "cartty_hstairs01_q_stair03", ["price"] = 0, ["label"] = "Q STAIR03" },
        [182] = { ["object"] = "cartty_hstairs01_q_stair04", ["price"] = 0, ["label"] = "Q STAIR04" },
        [183] = { ["object"] = "cartty_hstairs01_q_stair05", ["price"] = 0, ["label"] = "Q STAIR05" },
        [184] = { ["object"] = "cartty_hstairs01_q_stair06", ["price"] = 0, ["label"] = "Q STAIR06" },
        [185] = { ["object"] = "cartty_hstairs01_q_stair07", ["price"] = 0, ["label"] = "Q STAIR07" },
        [186] = { ["object"] = "cartty_hstairs01_q_stair08", ["price"] = 0, ["label"] = "Q STAIR08" },
        [187] = { ["object"] = "cartty_hstairs01_q_stair09", ["price"] = 0, ["label"] = "Q STAIR09" },
        [188] = { ["object"] = "cartty_hstairs01_q_stair10", ["price"] = 0, ["label"] = "Q STAIR10" },
        [189] = { ["object"] = "cartty_hstairs01_q_stair11", ["price"] = 0, ["label"] = "Q STAIR11" },
        [190] = { ["object"] = "cartty_hstairs01_q_stair12", ["price"] = 0, ["label"] = "Q STAIR12" },
        -- Rs
        [191] = { ["object"] = "cartty_hstairs01_r_stair03", ["price"] = 0, ["label"] = "R STAIR03" },
        [192] = { ["object"] = "cartty_hstairs01_r_stair04", ["price"] = 0, ["label"] = "R STAIR04" },
        [193] = { ["object"] = "cartty_hstairs01_r_stair05", ["price"] = 0, ["label"] = "R STAIR05" },
        [194] = { ["object"] = "cartty_hstairs01_r_stair06", ["price"] = 0, ["label"] = "R STAIR06" },
        [195] = { ["object"] = "cartty_hstairs01_r_stair07", ["price"] = 0, ["label"] = "R STAIR07" },
        [196] = { ["object"] = "cartty_hstairs01_r_stair08", ["price"] = 0, ["label"] = "R STAIR08" },
        [197] = { ["object"] = "cartty_hstairs01_r_stair09", ["price"] = 0, ["label"] = "R STAIR09" },
        [198] = { ["object"] = "cartty_hstairs01_r_stair10", ["price"] = 0, ["label"] = "R STAIR10" },
        [199] = { ["object"] = "cartty_hstairs01_r_stair11", ["price"] = 0, ["label"] = "R STAIR11" },
        [200] = { ["object"] = "cartty_hstairs01_r_stair12", ["price"] = 0, ["label"] = "R STAIR12" },
        -- Ss
        [201] = { ["object"] = "cartty_hstairs01_s_stair03", ["price"] = 0, ["label"] = "S STAIR03" },
        [202] = { ["object"] = "cartty_hstairs01_s_stair04", ["price"] = 0, ["label"] = "S STAIR04" },
        [203] = { ["object"] = "cartty_hstairs01_s_stair05", ["price"] = 0, ["label"] = "S STAIR05" },
        [204] = { ["object"] = "cartty_hstairs01_s_stair06", ["price"] = 0, ["label"] = "S STAIR06" },
        [205] = { ["object"] = "cartty_hstairs01_s_stair07", ["price"] = 0, ["label"] = "S STAIR07" },
        [206] = { ["object"] = "cartty_hstairs01_s_stair08", ["price"] = 0, ["label"] = "S STAIR08" },
        [207] = { ["object"] = "cartty_hstairs01_s_stair09", ["price"] = 0, ["label"] = "S STAIR09" },
        [208] = { ["object"] = "cartty_hstairs01_s_stair10", ["price"] = 0, ["label"] = "S STAIR10" },
        [209] = { ["object"] = "cartty_hstairs01_s_stair11", ["price"] = 0, ["label"] = "S STAIR11" },
        [210] = { ["object"] = "cartty_hstairs01_s_stair12", ["price"] = 0, ["label"] = "S STAIR12" },
        -- Ts
        [211] = { ["object"] = "cartty_hstairs01_t_stair03", ["price"] = 0, ["label"] = "T STAIR03" },
        [212] = { ["object"] = "cartty_hstairs01_t_stair04", ["price"] = 0, ["label"] = "T STAIR04" },
        [213] = { ["object"] = "cartty_hstairs01_t_stair05", ["price"] = 0, ["label"] = "T STAIR05" },
        [214] = { ["object"] = "cartty_hstairs01_t_stair06", ["price"] = 0, ["label"] = "T STAIR06" },
        [215] = { ["object"] = "cartty_hstairs01_t_stair07", ["price"] = 0, ["label"] = "T STAIR07" },
        [216] = { ["object"] = "cartty_hstairs01_t_stair08", ["price"] = 0, ["label"] = "T STAIR08" },
        [217] = { ["object"] = "cartty_hstairs01_t_stair09", ["price"] = 0, ["label"] = "T STAIR09" },
        [218] = { ["object"] = "cartty_hstairs01_t_stair10", ["price"] = 0, ["label"] = "T STAIR10" },
        [219] = { ["object"] = "cartty_hstairs01_t_stair11", ["price"] = 0, ["label"] = "T STAIR11" },
        [220] = { ["object"] = "cartty_hstairs01_t_stair12", ["price"] = 0, ["label"] = "T STAIR12" },
    },
},
